In [97]:
from gensim.models import Word2Vec
import numpy as np

# Import training data

In [10]:
import csv

trainingData = []

with open('./data/word2vec_train_data.csv') as file:
    train_file = csv.reader(file)
    
    for row in train_file:
        trainingData.append(row)
print('total len =', len(trainingData))

total len = 19332


In [89]:
import copy

trainingData_suffle = []

times = 10
for skills in trainingData:
    skills_ = skills
    for i in range(times):
        random.shuffle(skills_)
        skills_copy = copy.deepcopy(skills_)
        trainingData_suffle.append(skills_copy)
len(trainingData_suffle)

193320

# Co-occurrence Matrix

In [114]:
word_dict = {}
k = -1

for skills in trainingData:
    for skill in skills:
        if not(skill in word_dict):
            k += 1
            word_dict[skill] = k
total_skill = k + 1
print('total skill:', total_skill)

total skill: 2185


In [154]:
co_occur_mat = np.zeros((total_skill,total_skill))

for skills in trainingData:
    l = len(skills)
    for i in range(l):
        for j in range(l):
            if i != j:
                skill_a = skills[i]
                skill_b = skills[j]
                co_occur_mat[word_dict[skill_a]][word_dict[skill_b]] += 1.

In [155]:
count = np.sum(co_occur_mat, axis=1)
for i in range(len(count)):
    if count[i] == 0:
        count[i] = 1

co_occur_mat = (co_occur_mat.T / count).T

In [178]:
np.save('./data/co_occur.npy', co_occur_mat)

In [158]:
co_occur_mat[1]

array([3.32477451e-03, 0.00000000e+00, 2.61044177e-02, ...,
       0.00000000e+00, 0.00000000e+00, 3.29185595e-05])

In [161]:
co_occur_mat.shape

(2185, 2185)

# Model

In [90]:
model = Word2Vec(trainingData_suffle, size=32, window=20, min_count=1, workers=3)

In [177]:
model.save('./data/word2vec.model')

In [ ]:
model = Word2Vec.load('./data/word2vec.model')

In [95]:
print(['python','html'], model.wv.similarity('python','html'))
print(['css3','html'], model.wv.similarity('css3','html'))
print(['physics','mathematics'], model.wv.similarity('physics','mathematics'))

['python', 'html'] 0.0064916536
['css3', 'html'] 0.12708811
['physics', 'mathematics'] 0.7964257


In [92]:
model.wv.most_similar(positive=['physics'], topn=10)

[('mathematics', 0.7964256405830383),
 ('mathematica', 0.757845401763916),
 ('calculus', 0.7297621369361877),
 ('scientific-research', 0.7113232612609863),
 ('geology', 0.7097221612930298),
 ('teaching-algebra', 0.692982017993927),
 ('legal-translation', 0.6870766282081604),
 ('digital-signal-processing', 0.6813245415687561),
 ('computer-vision', 0.6722491383552551),
 ('linguistics', 0.6693482995033264)]

In [94]:
model.wv.most_similar(positive=['css'], topn=10)

[('fbml', 0.5594080686569214),
 ('css3', 0.5570359826087952),
 ('modx', 0.5312826633453369),
 ('skadate', 0.511943519115448),
 ('psd-to-xhtml', 0.5101155042648315),
 ('psd-to-html', 0.4957699775695801),
 ('psd-to-wordpress', 0.4899706244468689),
 ('psd-to-mailchimp', 0.48001211881637573),
 ('smarty', 0.4793943166732788),
 ('1shoppingcart', 0.4790232181549072)]

In [176]:
len(model.wv.vocab)

2185

In [ ]:
class CBOW(nn.Module):
    def __init__(self, totalSkill, dim=32):
        super(CBOW, self).__init__()
        
        self.embed = nn.EmbeddingBag(totalSkill, dim, mode='mean')
        self.decode = nn.Linear(dim, totalSkill, bias=False)
        
    def forward(self, x):
        h = self.embed(x)
        p = F.log_softmax(self.decode(x))
        return p
    def embedding(self, x):
        h = self.embed(x)
        return h
    def predict(self, x):
        return torch.exp(self.forward(x))

In [6]:
print(F.log_softmax(torch.Tensor([[1,2,3,4]])))
print(F.log_softmax(torch.Tensor([[1,2,3,4],[5,6,7,8]])))

tensor([[-3.4402, -2.4402, -1.4402, -0.4402]])
tensor([[-3.4402, -2.4402, -1.4402, -0.4402],
        [-3.4402, -2.4402, -1.4402, -0.4402]])


/home/yanbo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.
/home/yanbo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  


In [1]:
# 引入数据集
raw_sentences = ["the quick brown fox jumps over the lazy dogs","yoyoyo you go home now to sleep"]

# 切分词汇
sentences= [s.encode('utf-8').split() for s in raw_sentences]

In [2]:
sentences

[[b'the',
  b'quick',
  b'brown',
  b'fox',
  b'jumps',
  b'over',
  b'the',
  b'lazy',
  b'dogs'],
 [b'yoyoyo', b'you', b'go', b'home', b'now', b'to', b'sleep']]